apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateflow-deploy
  namespace: gateflow
spec:
  replicas: 2
  selector:
    matchLabels:
        app: gateflow
  template:
    metadata:
        labels:
           app: gateflow
    spec:
      containers:
        - name: gateflow
          image: lukassgx/gateflow:latest
          ports:
              - containerPort: 58925