apiVersion: v1
kind: Service
metadata:
   name: dispatch-service
   namespace: dispatch
spec:
    selector:
      app: dispatch
    ports:
       - port: 58925
         targetPort: 58925
    type: ClusterIP