services:
  app:
    container_name: app
    build:
      context: ../app
      dockerfile: Dockerfile
    restart: always
    ports:
      - 58925:58925
    networks:
      - gateflow_network

  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare
    restart: always
    command: tunnel --no-autoupdate run --token ${TOKEN}
    env_file:
      - .env
    environment:
      - TOKEN=${TOKEN}
    dns:
      - 1.1.1.1
      - 8.8.8.8
    networks:
      - gateflow_network

networks:
  gateflow_network:
      driver: bridge